# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(120, 40, 221, 51))
        font = QtGui.QFont()
        font.setFamily("一纸情书")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 110, 222, 94))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.username = QtWidgets.QLineEdit(self.layoutWidget)
        self.username.setObjectName("username")
        self.horizontalLayout_2.addWidget(self.username)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.register_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.register_2.setObjectName("register_2")
        self.horizontalLayout_3.addWidget(self.register_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.error = QtWidgets.QLabel(Dialog)
        self.error.setGeometry(QtCore.QRect(300, 145, 101, 16))
        self.error.setAutoFillBackground(False)
        self.error.setStyleSheet("color:red")
        self.error.setText("")
        self.error.setObjectName("error")
        self.time = QtWidgets.QLCDNumber(Dialog)
        self.time.setGeometry(QtCore.QRect(230, 210, 51, 61))
        self.time.setLineWidth(5)
        self.time.setDigitCount(1)
        self.time.setProperty("value", 8.0)
        self.time.setObjectName("time")
        self.tips = QtWidgets.QLabel(Dialog)
        self.tips.setGeometry(QtCore.QRect(90, 235, 121, 16))
        self.tips.setObjectName("tips")
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setGeometry(QtCore.QRect(360, 0, 47, 21))
        self.toolButton.setObjectName("toolButton")
        self.back = QtWidgets.QPushButton(Dialog)
        self.back.setGeometry(QtCore.QRect(10, 10, 41, 28))
        self.back.setObjectName("back")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "账号注册"))
        self.label_2.setText(_translate("Dialog", "账号:"))
        self.label.setText(_translate("Dialog", "密码:"))
        self.register_2.setText(_translate("Dialog", "注册"))
        self.tips.setText(_translate("Dialog", "即将返回登录界面"))
        self.toolButton.setText(_translate("Dialog", "..."))
        self.back.setText(_translate("Dialog", "返回"))
